Queue = []
Queue.append('człowiek')
Queue.append('baba')
Queue.append('dzieciak')
Queue.append('policjant')
print(Queue)
Queue.pop(0)
print(Queue)
Queue.insert (0, 'Dziewczyna')
print(Queue)
Queue.pop()
print(Queue)
